what-is-this: Jekyll的设置项，影响Markdown行为
# 页面框架设置见http://rs.kdxiaoyi.top/res/static/pages_sober/@3.1.0/-conf.js

# 网站的标题
title: 栈流Streack
# 网站描述
description: >-
  Streack Web Services
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: /favicon.ico
# 语言
lang: zh-cn
# google analytics
google_analytics: 

# 包含的文件
include:
  - _release/
  - assets/
  - doc/
  - h5event/
  - webtool
  - 404.html
  - index.html
  - LICENSE
  - pmd.js

# 不包含的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - jsconfig.json
  - readme.md

url: 'https://mc.kdxiaoyi.top'

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/Streack"

permalink: /:title/
paginate_path: /page:num/

# 以下为高级设置，非特殊请勿修改
# ADVANCED CONFIG BELOW. NO MODIFY WITHOUT SPECIAL CASE.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
theme: minima
livereload: true
debug: true